### ISSUE TITLE
TypeError: Object [object Object] has no method 'attachSchema' 

### ISSUE THREAD

**Issue by nabiltntn** [yogiben/meteor-notifications#1]
I am using Meteor 1.0 , and i getting this error in application startup after installing the package :
TypeError: Object [object Object] has no method 'attachSchema'

is it related to package dependencies versions ?

**Comment by samybob1** [comment]
The dependency is installed but I have the same error :

```
(STDERR) ~/.meteor/packages/meteor-tool/.1.0.40.yjc2g0++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
(STDERR) 						throw(ex);
(STDERR) 						      ^
(STDERR) TypeError: Object [object Object] has no method 'attachSchema'
(STDERR)     at __coffeescriptShare (packages/yogiben:notifications/lib/both/collections.coffee:45:15)
(STDERR)     at ~/[project dir]/.meteor/local/build/programs/server/packages/yogiben_notifications.js:103:4
(STDERR)     at ~/[project dir]/.meteor/local/build/programs/server/packages/yogiben_notifications.js:223:3
(STDERR)     at ~/[project dir]/.meteor/local/build/programs/server/boot.js:205:10
(STDERR)     at Array.forEach (native)
(STDERR)     at Function._.each._.forEach (~/.meteor/packages/meteor-tool/.1.0.40.yjc2g0++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
(STDERR)     at ~/[project dir]/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

I am using `Meteor 1.0.3.1`.

**Comment by mswilkison** [comment]
I'm getting the same error as @samybob1

**Comment by samybob1** [comment]
@yogiben Do you have an idea to solve this problem?

**Comment by samybob1** [comment]
Thanks @mswilkison!

I thought the `aldeed:simple-schema` dependency was installed when I installed the package :
```
$ meteor add yogiben:notifications
                                              
Changes to your project's package version selections:
                                              
aldeed:autoform        added, version 4.0.2   
aldeed:simple-schema   added, version 1.1.0
mrt:moment             added, version 2.8.1
yogiben:notifications  added, version 0.0.6

                                              
yogiben:notifications: Adds notification functionality
```

But the  `aldeed:simple-schema` dependency wasn't in `.meteor/packages`, I added it before `yogiben:notifications` and it's now working ;)

**Comment by rdewolff** [comment]
Had the same issue as well. Added the ```aldeed:simple-schema``` manually and it worked.
